# docker-compose/media/metube.yml
# NOTE: Self-hosted YouTube downloader. Replace volume path with your actual download directory.

version: "3"

services:
  metube:
    image: ghcr.io/alexta69/metube
    container_name: metube
    restart: unless-stopped
    ports:
      - "8081:8081"
    volumes:
      - /your/storage/path/data/Downloads/Youtube:/downloads
