# docker-compose/media/prowlarr.yml
# NOTE: Replace the volume path with your actual config directory.

services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - /your/storage/path/prowlarr/config:/config
    ports:
      - 9696:9696
    restart: unless-stopped