# docker-compose/media/unmanic.yml
# NOTE: Media library processor with GPU support. Replace volume paths with your own.

version: '2.4'

services:
  unmanic:
    container_name: unmanic
    image: josh5/unmanic:latest
    ports:
      - 8880:8888
    environment:
      - PUID=1000
      - PGID=1000
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - /your/storage/path/unmanic/config:/config
      - /your/storage/path/data:/library
      - /your/storage/path/unmanic/cache:/tmp/unmanic
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
