# docker-compose/infrastructure/flaresolverr.yml
# NOTE: Optional: Create a .env file to override PORT, LOG_LEVEL, LOG_HTML, etc.

version: "2.1"

services:
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Asia/Kolkata
    ports:
      - "${PORT:-8191}:8191"
    restart: unless-stopped
