# docker-compose/infrastructure/uptime-kuma.yml
# NOTE: Self-hosted monitoring tool. Replace volume path with your actual config path.

version: '3.3'

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    volumes:
      - /your/storage/path/uptime-kuma/config:/app/data
    ports:
      - 3001:3001 # <Host Port>:<Container Port>
    restart: always
